set(CPACK_DEB_COMPONENT_INSTALL ON)

set(CPACK_DEBIAN_ENABLE_COMPONENT_DEPENDS ON)
set(CPACK_DEBIAN_PACKAGE_SECTION "misc")

# Runtime package configuration
set(CPACK_DEBIAN_TEMPLATE01_RUNTIME_PACKAGE_NAME "template01")
set(CPACK_DEBIAN_TEMPLATE01_RUNTIME_FILE_NAME DEB-DEFAULT)
if (CMAKE_BUILD_TYPE STREQUAL "Debug" OR CMAKE_BUILD_TYPE STREQUAL "RelWithDebInfo")
    set(CPACK_DEBIAN_TEMPLATE01_RUNTIME_DEBUGINFO_PACKAGE ON)
endif()
set(CPACK_DEBIAN_TEMPLATE01_RUNTIME_PACKAGE_DEPENDS "espeak-ng-data (>= 1.51+dfsg)")
if(DEFINED VCPKG_INSTALLED_DIR)
    list(APPEND CPACK_DEBIAN_PACKAGE_SHLIBDEPS_PRIVATE_DIRS "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/lib")
endif()
set(CPACK_DEBIAN_TEMPLATE01_RUNTIME_PACKAGE_SHLIBDEPS ON)
set(CPACK_DEBIAN_TEMPLATE01_RUNTIME_PACKAGE_GENERATE_SHLIBS ON)

